rsconnect::deployApp(appName = "va-evictors-catalog", 
                     appFiles = c("app.R",
                                  "app-template.html",
                                  "app-data-notes",
                                  "app-orient-notes",
                                  "app-project-notes",
                                  "data-plaintiff-aggregated.txt",
                                  "data-monthly-plaintiff-aggregated.txt",
                                  "data-yearly-plaintiff-aggregated.txt",
                                  "www/styles.css",
                                  "www/plaintiff_courtnamesonly.csv",
                                  "www/EquityCenter-Logo_Typed_White.png",
                                  "www/EquityCenter-Logo_Typed_Black.png",
                                  "www/eclogo.png",
                                  "www/GitHub-Mark-Light-64px.png",
                                  "www/rvalogo-removebg.png",
                                  "www/rvalogo.jpg",
                                  "www/va-evictors-preview.png",
                                  "www/StatLab_logo_dark_background.png",
                                  "www/StatLab_logo_white_background.png"),
                     account = "virginiaequitycenter")