rsconnect::deployApp(appName = "va-evictors-catalog", 
                     appFiles = c("app.R",
                                  "app-template.html",
                                  "data-plaintiff-aggregated.txt",
                                  "data-monthly-plaintiff-aggregated.txt",
                                  "data-yearly-plaintiff-aggregated.txt",
                                  "html/app-data-notes",
                                  "html/app-orient-notes",
                                  "html/app-project-notes",
                                  "html/app-news",
                                  "html/selection-note-time",
                                  "html/footer",
                                  "html/app-data-notes-sp",
                                  "html/app-orient-notes-sp",
                                  "html/app-project-notes-sp",
                                  "html/news-sp",
                                  "html/selection-note-time-sp",
                                  "html/footer-sp",
                                  "html/head.html",
                                  "html/header",
                                  "translations/translation_sp.csv",
                                  "www/styles.css",
                                  "www/plaintiff_courtnamesonly.csv",
                                  "www/EquityCenter-Logo_Typed_White.png",
                                  "www/EquityCenter-Logo_Typed_Black.png",
                                  "www/eclogo.png",
                                  "www/GitHub-Mark-Light-64px.png",
                                  "www/rvalogo-removebg.png",
                                  "www/rvalogo.jpg",
                                  "www/va-evictors-preview.png",
                                  "www/StatLab_logo_dark_background.png",
                                  "www/StatLab_logo_white_background.png"),
                     account = "virginiaequitycenter")