# Aggregating eviction data by court and ZIP code
# Authors: Jacob Goldstein-Greenwood, Michele Claibourn
# Last revised: 2021-11-11

###############################################################################
# This code takes the cleaned data files generated by `clean-eviction-data.R` #
# (cases.csv and cases_non_residential.csv) and generates by-ZIP and by-court #
# summaries of the filings, plaintiff judgments, and default judgments        #
# - Two kinds of summaries are exported:                                      #
#   - Long summaries, with years stacked: by_zip.csv, by_court.csv,           #
#       by_zip_residential_only.csv, and by_court_residential_only.csv        #
#   - Wide summaries, with years spread: by_court_wide.csv and                #
#           by_court_residential_only_wide.csv                                #
#             - These wide files contain additional columns indicating        #
#                 % change year-to-year in cases, plaintiff judgments,        #
#                 and default judgments                                       #
# All exported summaries are placed in a new directory: `eviction-summaries`  #
###############################################################################

# Libraries
library(stringi)
library(tidyverse)

# Checks
if (any(stri_detect(dir(), regex = 'cases.csv')) == F | any(stri_detect(dir(), regex = 'cases_residential_only.csv')) == F) {
  stop('ensure that cases.csv and cases_residential_only.csv are in the working directory; did you run clean-eviction-data.R first?')
}

# Load data
cases <- read.csv('cases.csv')
cases_residential_only <- read.csv('cases_residential_only.csv')

# Summaries for all cases
by_court <- cases %>%
  group_by(filing_year, court_name) %>%
  summarize(cases = n(),
            plaintiff_judgments = sum(Judgment == 'Plaintiff'),
            default_judgments = sum(latest_hearing_result == 'Default Judgment')) %>%
  rename(court = court_name, year = filing_year) %>%
  ungroup()
by_zip <- cases %>%
  group_by(filing_year, def_1_zip) %>%
  summarize(cases = n(),
            plaintiff_judgments = sum(Judgment == 'Plaintiff'),
            default_judgments = sum(latest_hearing_result == 'Default Judgment')) %>%
  rename(ZIP = def_1_zip, year = filing_year) %>%
  ungroup()

# Summaries for residential only cases
by_court_residential_only <- cases_residential_only %>%
  group_by(filing_year, court_name) %>%
  summarize(cases = n(),
            plaintiff_judgments = sum(Judgment == 'Plaintiff'),
            default_judgments = sum(latest_hearing_result == 'Default Judgment')) %>%
  rename(court = court_name, year = filing_year) %>%
  ungroup()
by_zip_residential_only <- cases_residential_only %>%
  group_by(filing_year, def_1_zip) %>%
  summarize(cases = n(),
            plaintiff_judgments = sum(Judgment == 'Plaintiff'),
            default_judgments = sum(latest_hearing_result == 'Default Judgment')) %>%
  rename(ZIP = def_1_zip, year = filing_year) %>%
  ungroup()

# Convert by-court data from long to wide, filling in zeros for missing courts
widen <- function(x) {
  x <- pivot_wider(x, names_from = year,
                   values_from = c(cases, plaintiff_judgments, default_judgments),
                   names_glue  = '{.value}_{year}',
                   values_fill = 0)
  x
}
by_court_wide <- widen(by_court)
by_court_residential_only_wide <- widen(by_court_residential_only)

# %-change calculator
perc_change <- function(x) {
  yr_vec <- unique(stri_extract(colnames(x), regex = '\\d{4}')[stri_detect(colnames(x), regex = '\\d{4}')])
  yr_vec <- sort(yr_vec, decreasing = F)

  for (i in 2:length(yr_vec)) {
    x[, paste0('cases_percent_change_', yr_vec[i-1], '.', yr_vec[i])] <-
      round(((x[, paste0('cases_', yr_vec[i])] - x[, paste0('cases_', yr_vec[i-1])]) /
               x[, paste0('cases_', yr_vec[i-1])]) * 100,
            digits = 2)
  }
  for (i in 2:length(yr_vec)) {
    x[, paste0('plaintiff_judgments_percent_change_', yr_vec[i-1], '.', yr_vec[i])] <-
      round(((x[, paste0('plaintiff_judgments_', yr_vec[i])] - x[, paste0('plaintiff_judgments_', yr_vec[i-1])]) /
               x[, paste0('plaintiff_judgments_', yr_vec[i-1])]) * 100,
            digits = 2)
  }
  for (i in 2:length(yr_vec)) {
    x[, paste0('default_judgments_percent_change_', yr_vec[i-1], '.', yr_vec[i])] <-
      round(((x[, paste0('default_judgments_', yr_vec[i])] - x[, paste0('default_judgments_', yr_vec[i-1])]) /
               x[, paste0('default_judgments_', yr_vec[i-1])]) * 100,
            digits = 2)
  }
  x
}
by_court_wide <- perc_change(by_court_wide)
by_court_residential_only_wide <- perc_change(by_court_residential_only_wide)

# Create summaries folder to drop summaries in
summaries_dir <- 'eviction-summaries'
dir.create(summaries_dir)

# Export long by-court and by-ZIP files
by_export <- append(c('by_zip', 'by_court'), paste0(c('by_zip', 'by_court'), '_residential_only'))
sapply(by_export, function(x) write.csv(eval(parse(text = x)), file = paste0(summaries_dir, '/', x, '.csv'), row.names = F))

# Export wide by-court files with yearly % change indicated
write.csv(by_court_wide, file = paste0(summaries_dir, '/', 'by_court_wide.csv'), row.names = F)
write.csv(by_court_residential_only_wide, file = paste0(summaries_dir, '/', 'by_court_residential_only_wide.csv'), row.names = F)