---
title: "Serial Cases by Jurisdiction"
date: "10/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(plotly)

plaintiff_dat <- read.csv('plaintiff-database-Shiny/plaintiff-aggregated-data.txt', colClasses = 'character')
yearly_plaintiff_dat <- read.csv('plaintiff-database-Shiny/yearly-plaintiff-aggregated-data.txt', colClasses = 'character')

serial_all <- plaintiff_dat %>% 
  mutate(serial = as.numeric(cases_filed) - as.numeric(cases_filed_excluding_all_but_final_serial)) %>% 
  group_by(court_name) %>% 
  summarize(serial = sum(serial),
            cases = sum(as.numeric(cases_filed))) %>% 
  mutate(serial_percent = (serial/cases)*100,
         serial_percent = round(serial_percent, 1),
         court = str_remove(court_name, " General District Court"),
         court1 = fct_reorder(court, serial_percent),
         court2 = fct_reorder(court, serial))


serial_2021 <- yearly_plaintiff_dat %>% 
  filter(filing_year == "2021") %>% 
  mutate(serial = as.numeric(cases_filed) - as.numeric(cases_filed_excluding_all_but_final_serial)) %>% 
  group_by(court_name) %>% 
  summarize(serial = sum(serial),
            cases = sum(as.numeric(cases_filed)),
            mean_serial = mean(serial, na.rm = TRUE)) %>% 
  mutate(serial_percent = (serial/cases)*100,
         serial_percent = round(serial_percent, 1),
         court = str_remove(court_name, " General District Court"),
         court1 = fct_reorder(court, serial_percent),
         court2 = fct_reorder(court, serial))
```

## Serial Cases: 2018-2021 {.tabset}

### Percent
```{r, fig.height = 15, fig.width = 10}
per_all <- ggplot(serial_all, aes(y = court1, x = serial_percent)) +
  geom_point() +
  labs(x = "Percent of Cases that are Serial Filings", y = "",
       title = "Eviction Cases: Percent") +
  theme(axis.text.y = element_text(size = 7)) 

ggplotly(per_all)
```

### Number
```{r, fig.height = 15, fig.width = 10}
num_all <- ggplot(serial_all, aes(y = court2, x = serial)) +
  geom_point() +
  labs(x = "Number of Cases that are Serial Filings", y = "",
       title = "Eviction Cases: Number") +
  theme(axis.text.y = element_text(size = 7))

ggplotly(num_all)
```

## Serial Cases: 2021 {.tabset}

### Percent

```{r, fig.height = 15, fig.width = 10}
per_2021 <- ggplot(serial_2021, aes(y = court1, x = serial_percent)) +
  geom_point() +
  labs(x = "Percent of Cases that are Serial Filings", y = "",
       title = "Eviction Cases: Percent") +
  theme(axis.text.y = element_text(size = 7))

ggplotly(per_2021)
```

### Number

```{r, fig.height = 15, fig.width = 10}
num_2021 <- ggplot(serial_2021, aes(y = court2, x = serial)) +
  geom_point() +
  labs(x = "Number of Cases that are Serial Filings", y = "",
       title = "Eviction Cases: Number") +
  theme(axis.text.y = element_text(size = 7))

ggplotly(num_2021)
```